// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slicesy.PizzaOrder.WebApi.Repositories;

namespace Slicesy.PizzaOrder.WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    internal class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Slicesy.PizzaOrder.WebApi.Repositories.Models.Address", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("BuildingNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FlatNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PostalCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Street")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Address");
            });

            modelBuilder.Entity("Slicesy.PizzaOrder.WebApi.Repositories.Models.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<bool>("Active")
                    .HasColumnType("boolean");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<long?>("PermittedResourceId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("PizzaUser");
            });
#pragma warning restore 612, 618
        }
    }
}