version: "3.7"
services:
  db:
    image: "postgres:11"
    environment: 
      POSTGRES_USER: 'pizzaadmin'
      POSTGRES_PASSWORD: 'pizzasecret'
      POSTGRES_DB: 'pizzadb'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pizza_dbdata:/var/lib/postgresql/data
    container_name: "pizza_postgres"
    ports:
      - "5432:5432"
volumes:
  pizza_dbdata:
